REPR_VERBOSITY: 1
PARTITION_TYPE: 'TRI'
WELCOME_OFF: True
IIT_VERSION: "maximal-state-first"
REPERTOIRE_DISTANCE: "IIT_4.0_SMALL_PHI"
# RELATION_POTENTIAL_PURVIEWS: "WHOLE"
SYSTEM_PARTITION_TYPE: "TEMPORAL_DIRECTED_BI_CUT_ONE"
RELATION_PARTITION_AGGREGATION: "SUM"
RELATION_PARTITION_TYPE: "BI_CUT_ONE"
PROGRESS_BARS: False

RELATION_POTENTIAL_PURVIEWS: "WHOLE"
RELATION_COMPUTATION: "EXACT"
RELATION_APPROXIMATION: "SAMPLED_DEGREE_ONE"
RELATION_APPROXIMATION_SAMPLE_TIMEOUT: 1.0